import iconAutoFit from '@tabler/icons/outline/arrow-autofit-content.svg?raw';
import iconOrthographic from '@tabler/icons/outline/perspective-off.svg?raw';
import iconPerspective from '@tabler/icons/outline/perspective.svg?raw';
import iconGrid from '@tabler/icons/outline/grid-4x4.svg?raw';
import iconScale from '@tabler/icons/outline/scale.svg?raw';
import iconScissors from '@tabler/icons/outline/scissors.svg?raw';
import iconListTree from '@tabler/icons/outline/list-tree.svg?raw';
import iconFileImport from '@tabler/icons/outline/file-import.svg?raw';
import iconCopy from '@tabler/icons/outline/copy.svg?raw';
import iconCircleCheck from '@tabler/icons/outline/circle-check.svg?raw';
import iconRefresh from '@tabler/icons/outline/refresh.svg?raw';
import iconWand from '@tabler/icons/outline/wand.svg?raw';
import iconSun from '@tabler/icons/outline/sun.svg?raw';
import iconMoon from '@tabler/icons/outline/moon.svg?raw';
import iconEye from '@tabler/icons/outline/eye.svg?raw';
import iconEyeOff from '@tabler/icons/outline/eye-off.svg?raw';
import iconCircleHalf2 from '@tabler/icons/outline/circle-half-2.svg?raw';
import iconPlayerPause from '@tabler/icons/outline/player-pause.svg?raw';
import iconAlertTriangle from '@tabler/icons/outline/alert-triangle.svg?raw';

export const ICON_FIT = iconAutoFit;
export const ICON_ORTHO = iconOrthographic;
export const ICON_PERSP = iconPerspective;
export const ICON_GRID = iconGrid;
export const ICON_SCALE = iconScale;
export const ICON_SCISSORS = iconScissors;
export const ICON_LIST_TREE = iconListTree;
export const ICON_FILE_IMPORT = iconFileImport;
export const ICON_COPY = iconCopy;
export const ICON_CIRCLE_CHECK = iconCircleCheck;
export const ICON_REFRESH = iconRefresh;
export const ICON_WAND = iconWand;
export const ICON_SUN = iconSun;
export const ICON_MOON = iconMoon;
export const ICON_EYE = iconEye;
export const ICON_EYE_OFF = iconEyeOff;
export const ICON_SECTION_VIEW = iconCircleHalf2;
export const ICON_PAUSE = iconPlayerPause;
export const ICON_ALERT_TRIANGLE = iconAlertTriangle;
